# HermesGo green: launch Microsoft Visual Studio Code with Hermes agent wired in.
# Requires VS Code (not Cursor). Uses portable hermes.cmd + workspace under app\workspace.
param(
    [string]$WorkspaceRoot = "",
    [switch]$ApplyToWorkspace,
    [switch]$InstallExtension,
    [switch]$LaunchEditor,
    [switch]$NoLaunchEditor,
    [switch]$Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$HermesAgentExtensionId = "formulahendry.acp-client"

function Write-Info {
    param([string]$Message)
    if (-not $Quiet) { Write-Host $Message }
}

function Resolve-HermesAppRoot {
    param([string]$ScriptRoot)
    foreach ($candidate in @(
            $ScriptRoot,
            (Join-Path $ScriptRoot ".."),
            (Join-Path $ScriptRoot "..\..")
        )) {
        $full = [System.IO.Path]::GetFullPath($candidate)
        if (Test-Path -LiteralPath (Join-Path $full "runtime\python311\python.exe")) {
            return $full
        }
    }
    throw "HermesGo app root not found (expected runtime\python311\python.exe)."
}

function Escape-JsonString {
    param([string]$Value)
    return ($Value -replace '\\', '\\' -replace '"', '\"')
}

function Find-VSCodeCli {
    foreach ($name in @('code', 'code-insiders')) {
        $cmd = Get-Command $name -ErrorAction SilentlyContinue
        if ($cmd) {
            return @{ Name = $name; Path = $cmd.Source }
        }
    }

    foreach ($path in @(
            (Join-Path $env:LOCALAPPDATA 'Programs\Microsoft VS Code\bin\code.cmd'),
            (Join-Path ${env:ProgramFiles} 'Microsoft VS Code\bin\code.cmd'),
            (Join-Path ${env:ProgramFiles(x86)} 'Microsoft VS Code\bin\code.cmd')
        )) {
        if (Test-Path -LiteralPath $path) {
            return @{ Name = 'code'; Path = $path }
        }
    }

    foreach ($path in @(
            (Join-Path $env:LOCALAPPDATA 'Programs\Microsoft VS Code\Code.exe'),
            (Join-Path ${env:ProgramFiles} 'Microsoft VS Code\Code.exe'),
            (Join-Path ${env:ProgramFiles(x86)} 'Microsoft VS Code\Code.exe')
        )) {
        if (Test-Path -LiteralPath $path) {
            return @{ Name = 'code'; Path = $path; IsExe = $true }
        }
    }

    return $null
}

function Start-VSCodeWorkspace {
    param(
        [string]$WorkspaceFolder,
        [hashtable]$VSCode
    )

    if (-not $VSCode) { return $false }
    $ws = [System.IO.Path]::GetFullPath($WorkspaceFolder)
    if (-not (Test-Path -LiteralPath $ws)) {
        New-Item -ItemType Directory -Force -Path $ws | Out-Null
    }

    if ($VSCode.ContainsKey('IsExe') -and $VSCode.IsExe) {
        Start-Process -FilePath $VSCode.Path -ArgumentList @('--new-window', $ws) | Out-Null
    } elseif ($VSCode.Path -match '\.exe$') {
        Start-Process -FilePath $VSCode.Path -ArgumentList @('--new-window', $ws) | Out-Null
    } else {
        Start-Process -FilePath $VSCode.Path -ArgumentList @('--new-window', $ws) | Out-Null
    }
    return $true
}

$scriptDir = $PSScriptRoot
$appRoot = Resolve-HermesAppRoot -ScriptRoot $scriptDir
$pythonExe = Join-Path $appRoot "runtime\python311\python.exe"
$hermesCmd = Join-Path $appRoot "runtime\bin\hermes.cmd"
$registryDir = Join-Path $appRoot "runtime\hermes-agent\acp_registry"
$hermesHome = Join-Path $appRoot "home"
$editorDir = Join-Path $appRoot "editor\vscode"
$generatedSettings = Join-Path $editorDir "hermes-vscode.settings.json"
$guidePath = Join-Path $appRoot "docs\VSCODE-GREEN.md"

if (-not (Test-Path -LiteralPath $hermesCmd)) {
    throw "Missing portable CLI: $hermesCmd"
}
if (-not (Test-Path -LiteralPath (Join-Path $registryDir "agent.json"))) {
    throw "Missing Hermes editor registry: $registryDir"
}

$env:HERMES_PORTABLE_APP_ROOT = $appRoot
$env:HERMES_HOME = $hermesHome
$env:HERMES_DISABLE_WSL = "1"
$env:HERMES_PREFER_WINDOWS = "1"
$env:HERMESGO_STRICT_PORTABLE = "1"
$env:HERMES_PORTABLE_STRICT = "1"

$agentRoot = Join-Path $appRoot "runtime\hermes-agent"
$bootstrap = @"
import sys
sys.path.insert(0, r'$agentRoot')
from hermes_cli.portable_bootstrap import ensure_portable_acp_deps, ensure_portable_exe_ready
ensure_portable_exe_ready()
ensure_portable_acp_deps()
import acp
from acp.schema import AgentCapabilities
print('HERMES_VSCODE_OK')
"@
$bootOut = @(& $pythonExe -c $bootstrap 2>&1 | ForEach-Object { "$_" })
$ok = @($bootOut | Where-Object { $_ -match "HERMES_VSCODE_OK" })
if ($ok.Length -lt 1) {
    throw "Hermes VS Code runtime not ready. Output: $($bootOut -join ' ')"
}

$hermesCmdJson = Escape-JsonString $hermesCmd
$registryJson = Escape-JsonString $registryDir
$homeJson = Escape-JsonString $hermesHome

$settingsBody = @"
{
  "_comment": "HermesGo green portable - generated by Install-HermesVSCode.ps1",
  "acp.agents": {
    "HermesGo": {
      "command": "$hermesCmdJson",
      "args": ["acp"],
      "env": {
        "HERMES_HOME": "$homeJson",
        "HERMES_PORTABLE_APP_ROOT": "$(Escape-JsonString $appRoot)",
        "HERMES_DISABLE_WSL": "1",
        "HERMES_PREFER_WINDOWS": "1",
        "HERMESGO_STRICT_PORTABLE": "1"
      }
    }
  },
  "acpClient.agents": [
    {
      "name": "hermes-agent",
      "registryDir": "$registryJson"
    }
  ],
  "acp.defaultWorkingDirectory": "",
  "acp.logTraffic": false
}
"@

New-Item -ItemType Directory -Force -Path $editorDir | Out-Null
Set-Content -LiteralPath $generatedSettings -Value $settingsBody -Encoding utf8
Write-Info "[HermesGo] Wrote VS Code settings: $generatedSettings"

$doApply = $ApplyToWorkspace -or (-not $PSBoundParameters.ContainsKey('ApplyToWorkspace'))
$doInstallExt = $InstallExtension -or (-not $PSBoundParameters.ContainsKey('InstallExtension'))
$doLaunch = ($LaunchEditor -or (-not $PSBoundParameters.ContainsKey('LaunchEditor'))) -and -not $NoLaunchEditor

$workspaceFolder = $WorkspaceRoot
if ([string]::IsNullOrWhiteSpace($workspaceFolder)) {
    $workspaceFolder = Join-Path $appRoot "workspace"
}
$workspaceFolder = [System.IO.Path]::GetFullPath($workspaceFolder)

if ($doApply) {
    $vscodeDir = Join-Path $workspaceFolder ".vscode"
    New-Item -ItemType Directory -Force -Path $vscodeDir | Out-Null
    $dest = Join-Path $vscodeDir "settings.json"
    if (Test-Path -LiteralPath $dest) {
        $backup = "$dest.bak-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        Copy-Item -LiteralPath $dest -Destination $backup -Force
        Write-Info "[HermesGo] Backed up existing settings to $backup"
    }
    Set-Content -LiteralPath $dest -Value $settingsBody -Encoding utf8
    Write-Info "[HermesGo] Applied Hermes settings to workspace: $dest"
}

$vscode = Find-VSCodeCli

if ($doInstallExt -and $vscode) {
    try {
        & $vscode.Path --install-extension $HermesAgentExtensionId --force 2>&1 | Out-Null
        Write-Info "[HermesGo] Installed VS Code extension: $HermesAgentExtensionId"
    } catch {
        Write-Info "[HermesGo] Extension install skipped: $($_.Exception.Message)"
    }
} elseif ($doInstallExt) {
        Write-Info "[HermesGo] VS Code CLI not found - install extension from Marketplace after opening VS Code."
}

$launched = $false
if ($doLaunch) {
    if ($vscode) {
        $launched = Start-VSCodeWorkspace -WorkspaceFolder $workspaceFolder -VSCode $vscode
        if ($launched) {
            Write-Info "[HermesGo] Started Visual Studio Code: $workspaceFolder"
        }
    }
}

if (-not $Quiet) {
    Write-Host ""
    Write-Host "=== HermesGo + Visual Studio Code (green) ===" -ForegroundColor Cyan
    if ($launched) {
        Write-Host "VS Code is open. Sidebar: Hermes / Connect -> choose HermesGo"
        Write-Host "Or Ctrl+Shift+P -> type Connect -> pick HermesGo agent"
    } else {
        Write-Host "Could not start Visual Studio Code."
        Write-Host "Install VS Code (User or System): https://code.visualstudio.com/download"
        Write-Host "This launcher does NOT open Cursor - only Microsoft VS Code."
        Write-Host "After install, run HermesVSCode.bat again."
        Write-Host "Workspace folder: $workspaceFolder"
    }
    Write-Host ""
    Write-Host "Settings: $generatedSettings"
    if (Test-Path -LiteralPath $guidePath) {
        Write-Host "Guide:  $guidePath"
    }
    Write-Host ""
    if (-not $launched) {
        Write-Host "Press any key to close..."
        $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
    }
}

exit 0
